# General configuration ################################################################################################
project:
  name: "hyperscanning"

debug:
  enabled: false
  subjects: ["sub-006"]

subjects:
  pattern: "sub-*"
  exclude: [
             "sub-001",  # only 32-electrodes
             "sub-002",  # only 32-electrodes
             "sub-003",  # bad electrode placement
             # "sub-004",  # to match partners
             # "sub-031",  # to match partners
             "sub-032",   # bad signal
  ]
  missing_runs:
    sub-004:
      conversation: [ "1", "2" ]

tasks:
  include: ["conversation"]#, "resting"]

runs:
  include:
    conversation: [1,2,3,4,5,6,7,8]
    resting: [1,2]

eeg:
  sfreq_hz: 2048

annotations:
  "ipu": "ipu_v1"
