paths:
  bids_root: "/Users/hiro/Datasets/DUET-private"
  out_dir: "/Users/hiro/Datasets/working/duet-reviewing"
  lm_feature_root: "/Users/hiro/Datasets/working/duet-extra-data/converted_lm_features"
  results_root: "/Users/hiro/Datasets/working/duet"
  reports_root: "/Users/hiro/Datasets/working/duet/reports"
  precomputed_ica_root: "/Users/hiro/Datasets/working/duet-extra-data/precomputed_ica"
  annotation_root: "/Users/hiro/Projects/active/hyperscanning-working/data/annotations"
