viz:
  speech_artefact:
    task: "conversation"
    filename: "speech_artefact_summary.png"
    dpi: 300
    figsize:
      width: 20.0
      height: 4.5
    psd:
      method: "welch"
      fmin_hz: 1.0
      fmax_hz: 30.0
      n_fft: 256
  trf_score:
    task: "conversation"
    filename: "trf_score_summary.png"
    dpi: 300
    x_tick_label_scale: 0.7
    figsize:
      width: 13.0
      height: 4.5
    plotted_features:
      other_speech_envelope: envelope
      other_f1_f2: vowel
      other_f0: F0
      other_phoneme_onsets: phoneme
      other_syllable_onsets: syllable
      other_token_onsets: words
      other_surprisal: surprisal
      other_entropy: entropy
      other_word_class_onsets: POS
  trf_main_figure:
    task: "conversation"
    filename: "trf_main_figure_summary.png"
    dpi: 300
    panel_dpi: 240
    figsize:
      width: 18.0
      height: 18.0
    layout:
      rows: 3
      cols: 3
    joint_times_seconds: [0.10, 0.20, 0.35]
    joint_plot:
      line_width: 2.8
      font_scale: 3.0
      ylabel: "A.U."
      show_colorbar: false
      compact_vertical: true
    features:
      - predictor: other_speech_envelope
        label: envelope
        joint_times_seconds: [0.05, 0.16, 0.3]
      - predictors: [other_f1, other_f2]
        label: vowel
        joint_times_seconds: [0.05, 0.18, 0.40]
      - predictor: other_f0
        label: F0
        joint_times_seconds: [0.02, 0.15, 0.40]
      - predictor: other_phoneme_onsets
        label: phoneme
        joint_times_seconds: [0.08, 0.20, 0.5]
      - predictor: other_syllable_onsets
        label: syllable
        joint_times_seconds: [0.10, 0.35, 0.45]
      - predictor: other_token_onsets
        label: words
        joint_times_seconds: [0.20, 0.40, 0.55]
      - predictor: other_surprisal
        label: surprisal
        joint_times_seconds: [0.3, 0.40, 0.70]
      - predictor: other_entropy
        label: entropy
        joint_times_seconds: [0.20, 0.40, 0.70]
      - predictors: [other_function_word_onsets, other_content_word_onsets]
        label: POS
        joint_times_seconds: [0.20, 0.35, 0.50]
  ipu_turn_taking:
    filename: "ipu_turn_taking_summary.png"
    dpi: 300
    figsize:
      width: 24.0
      height: 7.5
